INSERT INTO customers (name, city, state, street, credit) values ('Juan Gustavo','Jundiai','Sao paulo', 'Rua do Alvares', 3000);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Maria Silva', 'São Paulo', 'São Paulo', 'Avenida Paulista', 2500);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Pedro Santos', 'Rio de Janeiro', 'Rio de Janeiro', 'Rua da Lapa', 3500);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Ana Souza', 'Belo Horizonte', 'Minas Gerais', 'Rua das Flores', 2800);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Carlos Oliveira', 'Brasília', 'Distrito Federal', 'Quadra 302', 4000);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Carlos Oliveira', 'Brasília', 'Distrito Federal', 'Quadra 302', 4000);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Fernanda Costa', 'Curitiba', 'Paraná', 'Rua XV de Novembro', 3200);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Rafaela Pereira', 'Fortaleza', 'Ceará', 'Avenida Beira Mar', 2700);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Gustavo Martins', 'Salvador', 'Bahia', 'Praça Castro Alves', 3800);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Patrícia Lima', 'Recife', 'Pernambuco', 'Rua do Bom Jesus', 3100);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Marcos Fernandes', 'Porto Alegre', 'Rio Grande do Sul', 'Rua dos Andradas', 2900);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Roberto Castro', 'Goiânia', 'Goiás', 'Avenida T-63', 3300);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Mariana Ferreira', 'Campo Grande', 'Mato Grosso do Sul', 'Avenida Afonso Pena', 3700);
INSERT INTO customers (name, city, state, street, credit) VALUES ('Mariana Ferreira', 'Campo Grande', 'Mato Grosso do Sul', 'Avenida Afonso Pena', 3700);
